---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stolon
  namespace: postgres
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - events
  verbs:
  - "*"
