---
kind: ConfigMap
apiVersion: v1
metadata:
  name: populate-database
  namespace: postgres
data:
  entrypoint.sh: |-
    #!/bin/bash
    sleep 100
    echo "stolon-proxy-service.stolon.svc.cluster.local:5432:*:*:$(cat /etc/secrets/stolon/password)" > /root/.pgpass
    chmod 0600 /root/.pgpass
    psql -h stolon-proxy-service.stolon.svc.cluster.local -U stolon -d postgres -c "CREATE USER myusername WITH PASSWORD 'mypassword';"
    psql -h stolon-proxy-service.stolon.svc.cluster.local -U stolon -d postgres -c "CREATE DATABASE mydb OWNER myusername;"
    psql -h stolon-proxy-service.stolon.svc.cluster.local -U stolon -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE mydb to myusername;"

---
kind: Job
apiVersion: batch/v1
metadata:
  name: stolon-initdb
  namespace: postgres
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 1000
  template:
    spec:
      initContainers:
      - name: wait-for-sentinel
        image: busybox
        command: ['sh', '-c', 'until nslookup stolon-proxy-service.stolon.svc.cluster.local; do echo waiting for sentinel; sleep 2; done;']
      containers:
      - name: initdb
        image: sorintlab/stolon:master-pg10
        command: ['/usr/local/bin/stolonctl', '--cluster-name=kube-stolon', '--store-backend=kubernetes', '--kube-resource-kind=configmap', '--kube-namespace=postgres', 'init', '--yes']
      - name: populate
        image: sorintlab/stolon:master-pg10
        command:
        - /bin/entrypoint.sh
        volumeMounts:
        - name: script-volume
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        - mountPath: /etc/secrets/stolon
          name: stolon-pass
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          defaultMode: 0700
          name: populate-database
      - name: stolon-pass
        secret:
          secretName: stolon
