---
kind: Service
apiVersion: v1
metadata:
  name: example-full
  namespace: example-full
  labels:
    app: example-full
spec:
  clusterIP: None
  ports:
  - name: http-service
    port: 8002
  selector:
    app: example-full
